import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useState } from "react";
import { Loader } from "../components/loader";
import styles from "../styles/Home.module.css";
import type { IPreviewData } from "../types/types";

const Home: NextPage = () => {
  const [url, setUrl] = useState<string>("");
  const [updatedUrl, setUpdatedUrl] = useState<string>("");
  const [urlError, setUrlError] = useState<string>("");
  const [previewData, setPreviewData] = useState<IPreviewData>();
  const [previewDataError, setPreviewDataError] = useState<unknown>();
  const [isLoading, setIsLoading] = useState(false);

  const isUrlValid = (url: string): void => {
    const urlRegEx =
      /^(https?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(\:\d+)?(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(\#[-a-z\d_]*)?$/i;

    if (urlRegEx.test(url)) {
      setUrlError("");
      return;
    }
    setUrlError("please enter valid url");
  };

  const urlChangeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPreviewData(undefined);
    setPreviewDataError(undefined);
    setUpdatedUrl("");
    if (e.target.value) {
      isUrlValid(e.target.value);
      setUrl(e.target.value);
    } else {
      setUrlError("");
      setUrl("");
    }
  };

  const onPreviewClick = useCallback(() => {
    let newUrl = url;
    if (!(url.startsWith("https://") || url.startsWith("http://"))) {
      newUrl = "https://" + newUrl;
    }
    setUpdatedUrl(newUrl);
    fetchData(newUrl);
  }, [url]);

  const fetchData = async (url: string) => {
    setIsLoading(true);
    fetch(`https://link-preview4.p.rapidapi.com/?url=${url}&oembed=false`, {
      method: "GET",
      headers: {
        "X-RapidAPI-Key": process.env.NEXT_PUBLIC_RAPIDAPI_KEY || "",
        "X-RapidAPI-Host": process.env.NEXT_PUBLIC_RAPIDAPI_HOST || "",
      },
    })
      .then((res) => res?.json())
      .then((data) => {
        setPreviewData(data);
        setIsLoading(false);
      })
      .catch((err) => {
        setIsLoading(false);
        setPreviewDataError(err);
        console.error(err);
      });
  };

  return (
    <>
      {isLoading && <Loader />}
      <div className={styles.container}>
        <Head>
          <title>Link Preview</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={styles.header}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/link.svg" alt="link" className={styles.linkIcon} />
          <h1 className={styles.title}>Welcome to Link Previewer!</h1>
        </header>
        <section className={styles.inputSection}>
          <div className={styles.inputMainWrapper}>
            <div className={styles.inputWrapper}>
              <input
                id="url"
                type="url"
                name="url"
                value={url}
                className={styles.input}
                onChange={urlChangeHandler}
                placeholder="Enter Valid URL"
                onKeyUp={(e) => {
                  if (
                    (e.code === "Enter" || e.code === "NumpadEnter") &&
                    !urlError &&
                    url
                  )
                    onPreviewClick();
                }}
              />
              <span className={styles.inputError}>{urlError}</span>
            </div>
            <button
              onClick={onPreviewClick}
              className={styles.button}
              disabled={!!urlError || !url}
            >
              See Preview
            </button>
          </div>
        </section>
        {previewData || previewDataError ? (
          <section className={styles.previewSection}>
            <div className={styles.previewCard}>
              {previewDataError ? (
                <div className={styles.previewCardError}>
                  <p>Oops!</p>
                  <p>something went wrong</p>
                  <p>please try again later</p>
                </div>
              ) : (
                <>
                  {previewData?.ogp?.["og:video:url"]?.[0] ||
                  previewData?.ogp?.["og:video:secure_url"]?.[0] ||
                  previewData?.seo?.["twitter:player"]?.[0] ? (
                    <embed
                      className={styles.previewCardImg}
                      src={
                        previewData?.ogp?.["og:video:url"]?.[0] ||
                        previewData?.ogp?.["og:video:secure_url"]?.[0] ||
                        previewData?.seo?.["twitter:player"]?.[0]
                      }
                    />
                  ) : (
                    <>
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        className={styles.previewCardImg}
                        src={
                          previewData?.ogp?.["og:image"]?.[0] ||
                          previewData?.seo?.["twitter:image"]?.[0] ||
                          "/placeholder.png"
                        }
                        alt={
                          previewData?.title ||
                          previewData?.ogp?.["og:title"]?.[0] ||
                          previewData?.seo?.title?.[0] ||
                          previewData?.seo?.["twitter:title"]?.[0] ||
                          "Title"
                        }
                      />
                    </>
                  )}
                  <div className={styles.previewCardDetails}>
                    <a
                      target="_blank"
                      href={updatedUrl}
                      rel="noopener noreferrer"
                      className={styles.previewCardLink}
                    >
                      {previewData?.ogp?.["og:site_name"]?.[0] ||
                        previewData?.seo?.["twitter:site"]?.[0] ||
                        url}
                    </a>
                    <a
                      target="_blank"
                      href={updatedUrl}
                      rel="noopener noreferrer"
                      className={styles.previewCardTitle}
                    >
                      {previewData?.title ||
                        previewData?.ogp?.["og:title"]?.[0] ||
                        previewData?.seo?.title?.[0] ||
                        previewData?.seo?.["twitter:title"]?.[0] ||
                        "Title"}
                    </a>
                    <p className={styles.previewCardDesc}>
                      {previewData?.ogp?.["og:description"]?.[0] ||
                        previewData?.seo?.description?.[0] ||
                        previewData?.seo?.["twitter:description"]?.[0] ||
                        "Description"}
                    </p>
                  </div>
                </>
              )}
            </div>
          </section>
        ) : (
          ""
        )}
      </div>
      <footer className={styles.footer}>
        <p className={styles.footerText}>
          Made by{" "}
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://thekruz.tech"
            className={styles.footerLink}
          >
            {`Kru'Z`}
          </a>
        </p>
      </footer>
    </>
  );
};

export default Home;
